Added dropdowns and colorpickers to the SceneEffectCategory stuff.
IllusionMods/IllusionModdingAPI pull request #77
Opened 2024-09-12 17:51 UTC by krypto5863

Threw these together real quick, I only tested in HS2 and KKS, so lemme know if fixes or changes need to be made.

2024-09-12 21:54 UTC, ManlyMarco requested changes
The changes look good, but whitespace got messed up with random tabs. Make sure your editor is set to using spaces for indents.

2024-09-12 22:40 UTC, krypto5863 commented
Should be fixed now, I'm a tab enjoyer. Might add a few more controls to this later.

2024-09-13 00:23 UTC, ManlyMarco commented
Do you want me to wait with reviewing until you finish adding them? You can mark the PR as a draft in that case.

2024-09-13 17:50 UTC, krypto5863 commented
Nah should be good to go now. Think I've done most of the simple stuff with this already.

2024-09-17 19:37 UTC, ManlyMarco commented on src/Shared.CharaStudio/Studio/UI/SceneEffectsCategory.cs
> +            _collapseSprite = Resources.FindObjectsOfTypeAll<Sprite>().FirstOrDefault(r => r.name.Equals("sp_sn_09_00_03"));
Why not do this?
```suggestion
            var allsprites = Resources.FindObjectsOfTypeAll<Sprite>();
            _expandSprite = allSprites.FirstOrDefault(r => r.name.Equals("sp_sn_09_00_05"));
            _collapseSprite = allSprites.FirstOrDefault(r => r.name.Equals("sp_sn_09_00_03"));
```

2024-09-17 19:41 UTC, ManlyMarco commented on src/Shared.CharaStudio/Studio/UI/SceneEffectsCategory.cs
> +            var allsprites = Resources.FindObjectsOfTypeAll<Sprite>();
```suggestion
            var allSprites = Resources.FindObjectsOfTypeAll<Sprite>();
```

2024-09-17 19:41 UTC, ManlyMarco approved these changes

2024-09-17 19:41 UTC, merged